### ISSUE TITLE
Feature Request: SSH with switch user after ssh login

### ISSUE THREAD

**Issue by ashscool** [warmuuh/mlog#1]
Hi @warmuuh ,

It would be an amazing if you can add another step to switch user after ssh login.
For example: 

- Login as user1 (ssh enabled user).
- Switch to user2 (ssh is not enabled on this user so I can't directly ssh to this user). 

Maybe add new keys in application properties with that user's username and password? 
Thanks!

**Comment by warmuuh** [comment]
hi @ashscool 
sadly, i stopped developing mlog in favor of [warmuuh/mlog2](https://github.com/warmuuh/mlog2) (which does not (yet) support this usecase of ssh/tail logging.  (as i currently dont have the need anymore in my day-to-day work.)
you can either fork mlog and add it yourself (shouldnt be too complicated) or create a plugin with that functionality for mlog2 which i am happy to help you with.
